"use client";
import { store } from "./redux/store";
import { Provider } from "react-redux";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/commoncomponents/navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>
          <Navbar />
          <Toaster />
          {children}
        </body>
      </Provider>
    </html>
  );
}
